document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"eng\" xmlns:position=\"http://www.w3.org/1999/xhtml\" xmlns:top=\"http://www.w3.org/1999/xhtml\"");
document.writeln("      xmlns:left=\"http://www.w3.org/1999/xhtml\" xmlns:margin-top=\"http://www.w3.org/1999/xhtml\"");
document.writeln("      xmlns:margin-left=\"http://www.w3.org/1999/xhtml\">");
document.writeln("");
document.writeln("<style>h1{ text-align: center }</style>");
document.writeln("<h1 style = \'font-family: SansSerif\'>Most Expensive Transfers by Position</br>in the English Premier League Post-Covid</h1>");
document.writeln("");
document.writeln("<style>h2{ text-align: center }</style><style>h2{font-size: 24px}</style>");
document.writeln("<h2 style = \'font-family: SansSerif\'>By: Eddie Rodriguez</h2>");
document.writeln("<p style = \'font-family: SansSerif\'>The world\'s most popular sport is a cash cow, particularly in Europe. Out of all the European domestic leagues the English Premier League -- also known as just the Premier League -- is known to be the richest league in terms of revenue.");
document.writeln("    During the 2019/2020 season, the Premier League brought in 3.5-million euros of revenue, down about 9% compared to the previous season. This was largely in part due to the Covid-19 outbreak that occurred in early 2020. Like much of the world,");
document.writeln("    the spread of Covid led to a shut-down of the league on March 13, 2020. The season resumed on June 17, 2020, with what became to be known as \"Project Restart\". Games were held behind closed doors, without fans, leading to matches being played");
document.writeln("    in empty stadiums that gave off an eerie, almost post-apocalyptic feel. Coaches barked orders at their players while those players would yell back and forth, communicating to each other on the pitch (this is what the English call the soccer");
document.writeln("    field). This was heard clear as day throughout the match given that spectators were not allowed in the stadium. Watching a match between Chelsea and Liverpool without the usual tens of thousands of fans deriding each other and the players");
document.writeln("    just doesn\'t quite give off the same feel. That said, fans were eager to return to a semblance of normalcy given how excruciatingly long the first few months of the pandemic felt.");
document.writeln("</p>");
document.writeln("<p style = \'font-family: SansSerif\'>");
document.writeln("    The football faithful continued to watch and support their favorite clubs from a far, at home. Without match day revenue from ticket sales or concession sales, it was obvious the league was not going to be as profitable as it was in the past.");
document.writeln("    At least not for the current season at hand. Clubs were hit hard financially and some players decided to go without pay for a few months in order for clubs to pay the wages of their other workers. Eventually this trickled down to how the transfers would");
document.writeln("    be handled because many clubs were suffering financially and didn\'t really have the means to go out and spend 30 million euros on a new player, and that\'s on the cheap end if you are looking to bring in a quality starter into the squad. Players looking");
document.writeln("    to move from their current clubs wondered what exactly their future would hold. Clubs were nervously looking for a spare ten to fifteen million euros in the couch cushion to be able to bring in new talent. With this money drought, the time for austerity");
document.writeln("    was imminent. If your looking to buy a player you better believe you weren\'t offering what the other club\'s valuation of that player was. Player transfer fees were high, bordering on criminal, given the transfer that set the world alight in 2017 that");
document.writeln("    saw the Brazilian superstar Neymar da Silva Santos Junior -- better known as Neymar -- move from FC Barcelona to Paris Saint-Germain FC for 222-million euros. You don\'t need to be mathematician to realize just how outrageous that number is. To put the");
document.writeln("    Neymar transfer fee into perspective, you could buy 148-million of Costco\'s infamous $1.50 hot dog and soda combo for the price of one Neymar (though I am still mourning the loss of the polish sausage being taken off the Costco menu).");
document.writeln("    It was known that the inflation on player transfer fees would have to come down, and that\'s exactly what ended up happening.");
document.writeln("</p>");
document.writeln("<p style = \'font-family: SansSerif\'>");
document.writeln("    The long and short of it all is that clubs still spent money on buying new players, just not as much or as many as before, particularly in the season that followed the initial Covid-19 outbreak. Clubs who were in better financial situations than others,");
document.writeln("    like Chelsea FC who had been given a transfer ban the season prior for playing unregistered youth players. Their transfer ban sanctioned the club from being able to sell or purchase new players for an entire season. The Premier League, like most other");
document.writeln("    European domestic leagues have two transfer windows, Summer and Winter, which allow clubs to move players around during a one to two month window. With an entire season\'s worth of money from 2018 to 2019 burning a hole in the pocket of then Chelsea");
document.writeln("    owner, Roman Abramovich, it seemed they were one of maybe one or two other clubs who were even in contention to sign big name players. Despite the measly 3.5-million euros of revenue, clubs have mostly gotten back to their spending ways.");
document.writeln("</p>");
document.writeln("<p style = \'font-family: SansSerif\'>");
document.writeln("    Let\'s take a look at the most expensive players by position in the Premier League from the 2019/2020 season to the 2021/2022 season. You may notice that one club in particular seems to be involved in the purchase of a few of the");
document.writeln("    most expesnive players by that position. In case you aren\'t familiar with each position, or what the abbreviation for each position, see the image below showing which positions are located where on the pitch and what their general role is. The bar chart below gives a visual representation of each position and their maximum fee. You will find that if you click on any bar you will be linked with an article to");
document.writeln("    the player who was deemed worth splashing the cash on for that amount indicated in the chart. You can also follow the links at the bottom of the page to see the full list of player transfers, separated by Summer and Winter windows, for each season indicated");
document.writeln("</p>");
document.writeln("");
document.writeln("<body onload=\'init()\'>");
document.writeln("<div style=\"text-align: center\"></br><img id=\"Soccer Positions\" src=\"442 Soccer Formation.jpg\" alt=\"433 Formation - Player Positions\" width=\'900\' height=\'450\'></div>");
document.writeln("");
document.writeln("");
document.writeln("<div style=\"text-align:center\"><div style=\"font-size: 16px\"><p style = \"font-family:Arial\";>Above: Player positions and a brief explanation of their role.</p></div>");
document.writeln("<br /><br />");
document.writeln("<style>h3{ text-align: center } </style>");
document.writeln("<h3 style = \"font-family: SansSerif\">Does It Pay To Play Forward?</h3>");
document.writeln("");
document.writeln("");
document.writeln("<style>h4{font-size: 16px}</style><style>h4{ text-align: center }</style>");
document.writeln("    <h4 style = \"font-family: SansSerif\" ><u>HIGHEST TRANSFER FEE BY POSITION FROM 2019 TO 2022</u></h4>");
document.writeln("");
document.writeln("<script src=\'https://d3js.org/d3.v5.min.js\'></script>");
document.writeln("<svg width=\'900\' height=\'450\'></svg>");
document.writeln("");
document.writeln("<body>");
document.writeln("<style>");
document.writeln("    .bar {fill:seagreen;}");
document.writeln("    svg text { fill:black; font: 14px SansSerif; align-self: center}");
document.writeln("    svg {display: block; margin: 0 auto; margin-top: 25px}");
document.writeln("</style>");
document.writeln("");
document.writeln("<script>");
document.writeln("");
document.writeln("    var data = d3.csv(\'EPLTransferData.csv\').then(function(data) {");
document.writeln("        data.forEach(function(d) { d.fee =+ d.fee})");
document.writeln("        data.sort(function (a,b) { return d3.descending(a.fee, b.fee); })");
document.writeln("");
document.writeln("");
document.writeln("        var svg = d3.select(\'svg\'),");
document.writeln("            margin = 0.15 * svg.attr(\'height\'),");
document.writeln("            height = svg.attr(\'height\') - 2 * margin,");
document.writeln("            width = svg.attr(\'width\') - 2 * margin;");
document.writeln("");
document.writeln("        var xScale = d3.scaleLinear()");
document.writeln("            .domain([0, d3.max(data, function (d) {");
document.writeln("                return d.fee;");
document.writeln("            })])");
document.writeln("            .range([0, width]);");
document.writeln("");
document.writeln("        var yScale = d3.scaleBand()");
document.writeln("            .domain(data.map(function (d) {");
document.writeln("                return d.pos;");
document.writeln("            }))");
document.writeln("            .range([0, height]).padding(0.125);");
document.writeln("");
document.writeln("        g = svg.append(\'g\')");
document.writeln("            .attr(\'transform\', \'translate(\' + margin + \', \' + height + \')\')");
document.writeln("            .call(d3.axisBottom(xScale));");
document.writeln("");
document.writeln("        g = svg.append(\'g\')");
document.writeln("            .attr(\'transform\', \'translate(\' + margin + \', 0)\')");
document.writeln("            .call(d3.axisLeft(yScale));");
document.writeln("");
document.writeln("        g.selectAll(\'.bar\')");
document.writeln("            .data(data)");
document.writeln("            .enter().append(\'rect\')");
document.writeln("            .attr(\'class\', \'bar\')");
document.writeln("            .attr(\'y\', function (d) {");
document.writeln("                return yScale(d.pos);");
document.writeln("            })");
document.writeln("            .attr(\'x\', 0)");
document.writeln("            .attr(\'height\', yScale.bandwidth())");
document.writeln("            .attr(\'width\', function (d) {");
document.writeln("                return xScale(d.fee);");
document.writeln("            })");
document.writeln("            .on(\'mouseover\', function (d) {");
document.writeln("                return d3.select(this)");
document.writeln("                    .style(\'fill\', \'red\');");
document.writeln("            })");
document.writeln("            .on(\'mouseout\', function (d) {");
document.writeln("                return d3.select(this)");
document.writeln("                    .style(\'fill\', \'seagreen\');");
document.writeln("            })");
document.writeln("            .on(\'click\',function (d) {");
document.writeln("                if (d.pos == \'LW\')");
document.writeln("                location.replace(\'https://theathletic.com/news/manchester-city-sign-jack-grealish-from-aston-villa-in-100m-deal/6MmWdrEBXXhR/\')");
document.writeln("                if (d.pos === \'ST\')");
document.writeln("                location.replace(\'https://theathletic.com/news/chelsea-complete-115m-signing-of-romelu-lukaku-from-inter-milan/v28zOFCWr1R2/\')");
document.writeln("                if (d.pos == \'CB\')");
document.writeln("                    location.replace(\'https://theathletic.com/1116314/2019/08/05/woodward-was-quoted-80m-for-maguire-in-may-and-paid-it-in-august-heres-what-really-happened-in-between/\')");
document.writeln("                if (d.pos == \'RW\')");
document.writeln("                    location.replace(\'https://www.skysports.com/football/news/11670/11773463/nicolas-pepe-completes-move-to-arsenal-from-lille-for-club-record-72m\')");
document.writeln("                if (d.pos == \'AM\')");
document.writeln("                    location.replace(\'https://theathletic.com/2044050/2020/09/05/havertz-transfer-mclachlan-marina-phone-call-lampard-real-madrid/\')");
document.writeln("                if (d.pos == \'RB\')");
document.writeln("                    location.replace(\'https://www.skysports.com/football/news/11679/11779133/joao-cancelo-joins-man-city-from-juventus-with-danilo-moving-to-italian-club\')");
document.writeln("                if (d.pos == \'DM\')");
document.writeln("                    location.replace(\'https://www.skysports.com/football/news/11679/11779133/joao-cancelo-joins-man-city-from-juventus-with-danilo-moving-to-italian-club\')");
document.writeln("                if (d.pos == \'CM\')");
document.writeln("                    location.replace(\'https://theathletic.com/1481181/2019/12/29/ndombele-did-something-no-one-else-has-this-season-he-drove-spurs-forwards/\')");
document.writeln("                if (d.pos == \'LB\')");
document.writeln("                    location.replace(\'https://theathletic.com/2014012/2020/08/21/chelsea-close-to-50m-deal-for-leicester-left-back-chilwell/\')");
document.writeln("                if (d.pos == \'GK\')");
document.writeln("                    location.replace(\'https://theathletic.com/2779226/2021/08/20/why-arsenal-signed-aaron-ramsdale/\')");
document.writeln("                if (d.pos == \'LM\')");
document.writeln("                    location.replace(\'https://theathletic.com/news/brighton-transfers-marc-cucurella-roma/oPL2rFrAM3XX/\')");
document.writeln("                if (d.pos == \'RM\')");
document.writeln("                    location.replace(\'https://theathletic.com/news/victor-moses-chelsea-transfer-spartak-moscow/dk9OKQjS3kGt/\')");
document.writeln("            });");
document.writeln("");
document.writeln("// Axes Labels");
document.writeln("        svg.append(\'text\')");
document.writeln("            .attr(\'class\', \'x label\')");
document.writeln("            .attr(\'text-anchor\', \'center\')");
document.writeln("            .attr(\'x\', 0.5 * width)");
document.writeln("            .attr(\'y\', height + 0.75 * margin)");
document.writeln("            .text(\'Transfer Fee (Million Euros)\');");
document.writeln("");
document.writeln("        svg.append(\'text\')");
document.writeln("            .attr(\'class\', \'y label\')");
document.writeln("            .attr(\'text-anchor\', \'end\')");
document.writeln("            .attr(\'x\', -0.5 * (height - margin))");
document.writeln("            .attr(\'y\', 0.25 * margin)");
document.writeln("            .attr(\'transform\', \'rotate(-90)\')");
document.writeln("            .text(\'Player Position\');");
document.writeln("");
document.writeln("    })");
document.writeln("");
document.writeln("");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("    <style>h5{font-size: 24px}</style><style>h5{ text-align: center }</style><style>h5{ font-family:SansSerif }</style>");
document.writeln("    <h5>Player Transfer Sales & Purchases by Year</h5>");
document.writeln("    <style>h6{font-size: 18px}</style><style>h6{ font-family: SansSerif }</style><h6>2019/2020 Season Transfers</h6>");
document.writeln("    <a href=\"https://www.skysports.com/football/news/11095/11713244/premier-league-ins-and-outs-all-the-2019-summer-transfer-window-moves\">Summer 2019 per Sky Sports</a>");
document.writeln("    <br/><a href=\"https://www.skysports.com/football/news/11095/11898590/premier-league-ins-and-outs-the-2020-january-transfer-window-moves\">Winter 2020 per Sky Sports</a>");
document.writeln("    <style>h6{font-size: 18px}</style><style>h6{ font-family: SansSerif }</style><h6>2020/2021 Season Transfers</h6>");
document.writeln("    <a href=\"https://www.skysports.com/football/news/11661/12037288/premier-league-ins-and-outs-the-2020-summer-transfer-window-moves\">Summer 2021 per Sky Sports</a>");
document.writeln("    <br/><a href=\"https://www.skysports.com/football/news/11669/12174800/january-transfer-window-2021-premier-league-ins-and-outs\">Winter 2021 per Sky Sports</a>");
document.writeln("    <style>h6{font-size: 18px}</style><style>h6{ font-family: SansSerif }</style><h6>2021/2022 Season Transfers</h6>");
document.writeln("    <a href=\"https://www.skysports.com/football/news/11095/12312527/transfer-news-summer-transfer-window-2021-premier-league-ins-and-outs\">Summer 2021 per Sky Sports</a>");
document.writeln("    <br/><a href=\"https://www.skysports.com/football/news/11095/12482997/transfer-news-january-transfer-window-2022-premier-league-ins-and-outs\">Winter 2022 per Sky Sports</a>");
document.writeln("</html>");